#!/bin/sh
apt update -y
apt upgrade -y
apt install firefox -y
apt install tor -y
apt install wget -y
cd Downloads
wget https://dllb2.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE2MTE2MTk0MzIiLCJ1IjpudWxsLCJsdCI6ImRvd25sb2FkIiwicyI6ImY5ZTBlOWJiOWY4NWUzMzRmOGZiNWZlZTIxZGIxZGY1OTE5MmQzMGY4NWI4NTRkYWRlNTM5MzA4MGNmODM0ZGFiNjNhMzU0OTI4ZGJlYWZlYjY0YTAxNGYwZTkwOTVkNWE2ZWZhNTNjMWVkODE2YzlmYmFhN2EwMDk4OGUwYWM3IiwidCI6MTYyNDE0NDYwOCwic3RmcCI6IjI3MzdmZDY3ZTU5NGJhNzgwNDU2NDE3Mjg4MDhlZTgyIiwic3RpcCI6IjQ1LjIwLjIxNy4yMyJ9.swIh6a-Dl4BoHqZlbUtb5kld9GH475xQuGROdYBFDPE/Redmond97.tar.gz
wget https://dllb2.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE1OTE5Mzg5NjAiLCJ1IjpudWxsLCJsdCI6ImRvd25sb2FkIiwicyI6IjIwYWRmNjA3YTkyMDMzNmZjZWQ2ZjhhZWNjYWE3ZTMzMGU2NjdmNmY1NGEwNjMwZGJhYTE3YTRkNmZmZjJlZDUwMzUxMjlhMjRmNjZhOGRjYjFhNDNiZGNiZWJmN2ZmMDhiMmQ4ZTYyM2YyYjg5Zjk1ZmJiMDk0OTFkMmVlMTU4IiwidCI6MTYyNDE0NDYyOSwic3RmcCI6IjI3MzdmZDY3ZTU5NGJhNzgwNDU2NDE3Mjg4MDhlZTgyIiwic3RpcCI6IjQ1LjIwLjIxNy4yMyJ9.pl3Com9Divhi_QD0b3WNjZVrL51VxGHvm9XPF3RUhdg/Redmond97-icons.tar.gz
wget https://dllb2.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE2MTE1NzA3NDQiLCJ1IjpudWxsLCJsdCI6ImRvd25sb2FkIiwicyI6ImM2ZTc4M2M0ZGQ5ZmM0MGRjY2U4OTg2OTI4MmFjM2U5ZTZhZGEzZmU3NzJjZTMzYTg1NDFhM2YyYmMwOGFkODNiYWI5NDIzYmJhYzM4YzA3NjU2MDY3ODJmZjk4NzI5YWVkNmUyNDViOTBiOWVjY2Y3ZTFkYWYzNGRiYTQzZmU4IiwidCI6MTYyNDE0NDY0MCwic3RmcCI6IjI3MzdmZDY3ZTU5NGJhNzgwNDU2NDE3Mjg4MDhlZTgyIiwic3RpcCI6IjQ1LjIwLjIxNy4yMyJ9.GAxiel48W-jtTmHm7xs_GtzBBnGihWvaS6hCLi_l8dM/Redmond-firefox.tar.gz
apt install tor-browser -y
apt install tor-launcher -y
apt install libreoffice -y
apt install thunderbird -y
apt install gimp -y